plugins {
    id 'com.android.library'
}

// AAR file name: libzt-<buildType>.aar (expected by build.sh android-aar)
base {
    archivesName = 'libzt'
}

android {
    namespace 'com.zerotier.sockets'
    compileSdk 35
    ndkVersion '27.3.13750724'

    defaultConfig {
        minSdk 21
        externalNativeBuild {
            cmake {
                arguments "-DZTS_ENABLE_JAVA=ON"
            }
        }
        ndk {
            // ABIs to build and package into the AAR
            abiFilters "armeabi-v7a", "arm64-v8a", "x86", "x86_64"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    externalNativeBuild {
        cmake {
            path "../../../CMakeLists.txt"
            version '3.22.1'
        }
    }

    sourceSets {
        main {
            java {
                srcDir '../../../src/bindings/java'
            }
        }
    }
}
