name: Build NuGet Package

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      retention-days:
        type: number
        default: 14

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v7
      with:
        submodules: recursive

    - name: Build Package
      run: . .\build.ps1; BuildNuGetPackage -BuildType "Release" -Arch "x64" -Version "$(cat .\pkg\nuget\version.in)"

    - uses: actions/upload-artifact@v7
      with:
        name: libzt-nuget
        path: dist/win-x64-nuget-release/*.nupkg
        if-no-files-found: error
        retention-days: ${{ inputs.retention-days || 14 }}
